CA1_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls')),
    path('shop/', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('order/', include('order.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='cart_add'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/<uuid:product_id>/', views.full_remove, name='cart_clear'),
]

search/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name = 'search'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='searchResult')
]

shop/urls.py
from django.urls import path
from .views import ProdCat, ProdDetail

app_name = 'shop'

urlpatterns = [
    path('', ProdCat.as_view(), name='allProdCat'),
    path('<uuid:category_id>/', ProdCat.as_view(), name='products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', ProdDetail.as_view(), name='prod_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])

    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:prod_detail', args=[self.category.id, self.id])
    
    def __str__(self):
        return self.name

shop/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.views.generic import ListView, DetailView
from django.core.paginator import Page, Paginator, EmptyPage, InvalidPage

# Create your views here.

class ProdCat(ListView):
    model = Product
    def get(self,request, category_id=None):
        category = None
        products = None
        if category_id != None:
            category = get_object_or_404(Category, id = category_id)
            products = Product.objects.filter(category = category, available = True)
        else:
            products = Product.objects.all().filter(available = True)
        
        paginator = Paginator(products, 6)
        try:
            page = int(request.GET.get('page','1'))
        except:
            page = 1
        try:
             products = paginator.page(page)
        except (EmptyPage, InvalidPage):
            products = paginator.page(paginator.num_pages)
        
        return render(request,"shop/category.html",{'category':category, 'products':products})


class ProdDetail(DetailView):
    model = Product

    def get(self, request, category_id, product_id):
        try:
            product = Product.objects.get(category_id = category_id, id = product_id)
        except Exception as e:
            raise e
        return render(request, "shop/product.html", {'product':product})

templates/shop/category.html
{% extends "base.html" %}
{% load static %}

{% block metadescription %}
{% if category %}
    {{ category.description|truncatewords:155 }}
{% else %}
    Welcome to our store.
{% endif %}
{% endblock %}

{% block title %}
{% if category %}
    {{ category.name }} - Merch Store
{% else %}
    See our range of Merch
{% endif %}
{% endblock %}

{% block content %}
<!--Breadcrumb navigation-->
<div class="row text-light w-100">
<div class="col-1"></div>
<div class="col-10 container card bg-dark p-3 m-3">
    <form class="d-flex m-auto" action="{% url 'search:searchResult' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    {% if category %}
    <div class="row">
        <div class="mx-auto">
            <p><a href="{% url 'shop:allProdCat' %}">Our Product Collection</a> | {{category.name}}</p>
        </div>
    </div>
    {% endif %}
    <div class="card bg-dark p-3 m-3">
        {% if category %}
        <img src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div>
        <h1 class="text-center">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
    <img class="container" src="{% static 'images/storebanner.png' %}"
        style="height: 24em;" alt="Our Products Collection">
    <br>
    <div>
        <h1 class="text-center">All Products</h1>
        <p class="text-center">Find the perfect memorabilia for you</p>
    </div>
</div>

{% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="col-9 col-lg-4 col-sm-12 col-md-4">
            <div class="card text-center text-dark mt-2">
                <a class="img" href="{{product.get_absolute_url}}"><img class="card-img-top my_img" src="{{product.image.url}}" alt="{{product.name}}"
                    style="max-width: 400px; max-height: 350px; width: 100%;"></a>
                <div class="card-body border-top">
                    <h4>{{product.name}}</h4>
                    <p>€{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}"
                class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
</div>
</div>
{% endblock %}

templates/shop/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
{{ product.name }} - Perfect Cushion Store
{% endblock %}
{% block content %}
<h5><a class="ml-3" href="{% url 'shop:allProdCat' %}">
        <- Back</a>
</h5>
<div class="row w-100">
    <div class="container m-auto col-10">
        <div class="card d-flex flex-nowrap bg-dark rounded p-3">
            <div class="shadow w-100 bg-light d-inline-block">
                <div class="card shadow m-1">
                    <h1 class="card-title text-center">{{ product.category }}</h1>
                </div>
                <div class="float-left">
                    <img class="shadow m-2 img-thumbnail" src="{{ product.image.url }}"alt="{{ product.name }}" style="height:35em; width:40em">
                </div>
                <div class="card-body text-center">
                <h2 class="">{{product.name}}</h2>
                <p>£{{product.price}}</p>
                <p class="text-secondary">Description;</p>
                <p class="">{{product.description}}</p>
                <br>
                {% if product.stock == 0%}
                <p class="text-warning"><b>Out of Stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:cart_add' product.id %}">Add to Cart</a>
                {% endif %}
                </div>
            </div>
            {% endblock %}